<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
</div>
<div class="row">

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Director</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
<?php 
    if(count($posts) > 0 ) 
        {
            foreach ($posts as $key => $post) {
    ?>
    <tr>
      <th scope="row"><?= $post->getId();?></th>
      <td><?= $post->getTitle();?></td>
      <td width="500px;"><?= $post->getDescription();?></td>
      <td><?= $post->getDirector();?></td>
      <td role="cell">
            <button type="button" class="btn btn-success"><i class="fa fa-eye"></i></button>
            <button type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button>
       </td>
    </tr>
   <?php 
            }
        }else{
    ?>    
    <tr>
      <td colspan='6'>No record found.</td>
    </tr>
<?php        
    }    
 ?> 
  </tbody>
</table>
</div>

